version: '3'

services:
    home-assistant:
      image: homeassistant/home-assistant
      ports:
        - 8123:8123
      volumes:
        - ./home-assistant:/config

    unifi-video:
      image: pducharme/unifi-video-controller
      cap_add:
        - SYS_ADMIN
      volumes:
        - unifi-video-logs:/var/log/unifi-video

    unifi-video-publisher:
      image: tbro/logs-to-mqtt-publisher
      volumes:
        - unifi-video-logs:/var/log/unifi-video
        - ./logs-to-mqtt-publisher:/logs-to-mqtt-publisher
      environment:
        OPTIONS_FILE_PATH: '/logs-to-mqtt-publisher/options.json'

    mqtt-broker:
      image: eclipse-mosquitto
      volumes:
        - ./mosquitto/config:/mosquitto/config

volumes:
    unifi-video-logs:
