default_config:

mqtt:
  broker: mqtt-broker
  port: 1883
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
